-- Seed de clientes migrados desde althea_crm_clientes_v12_6.html
-- Ejecutar DESPUES de schema.sql

insert into public.clientes (comitente, nombre, apellido, fecha, asesor, team, reasignacion, perfil, reunion, obs, sub_panel, asesor_original, derivado, c_ordenes, usuario_c) values
  ('264620', 'Nicolas Alejandro', 'Casalis', '2019-03-28', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('280147', 'Maria Candela', 'Longhi', '2019-09-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('281838', 'Alan', 'Lavanchy', '2019-09-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('31999', 'Martinez Ezequiel Ma', 'Ercoreca', '2019-09-12', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('293140', 'Milena', 'Tedeschi', '2019-10-07', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('309749', 'Gauna Marien', 'Almau', '2020-01-08', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('338198', 'Pablo Sebastian', 'Calabrano', '2020-07-15', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('357537', 'Valeria Adriana', 'Fourment', '2020-11-06', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('369257', 'Santiago Enrique', 'Jojot', '2021-01-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('374724', 'Nicolas', 'Genaro', '2021-02-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('380082', 'Felipe Ezequiel', 'Vacchiani', '2021-03-25', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('383687', 'Hector Adrian', 'Taborda', '2021-04-26', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('389962', 'Felipe Valentin', 'Cabral', '2021-06-08', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('390616', 'Brenda Antonella', 'Rosano', '2021-06-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('391957', 'Lucas David', 'Furlani', '2021-06-23', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('392280', 'Alexis Adrian', 'Sosa', '2021-06-24', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('393416', 'Patricio', 'Biagini', '2021-06-30', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('395726', 'Mirta Alejandra Y/O Escobar Ana Paula', 'Schiro', '2021-07-13', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('400478', 'Perez Elizabeth Mirella', 'Arevalo', '2021-08-03', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('403083', 'Giovanni Mónica Lorena', 'De', '2021-08-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('406832', 'Facundo Nestor Ceferino', 'Acuña', '2021-09-06', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('409199', 'Anibal César', 'Paz', '2021-09-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('411692', 'Mariano Sebastian', 'Molina', '2021-10-04', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('411778', 'Fernandez Carlos Marcelo', 'Palacio', '2021-10-04', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('411927', 'Marcelo David', 'Rodriguez', '2021-10-05', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('414990', 'Carina Elisabet', 'Gohlke', '2021-10-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('415543', 'Monica Elizabeth', 'Cinalli', '2021-10-26', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('420163', 'Guiñez Pamela Karina', 'Hauenstein', '2021-11-12', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('421053', 'Domingo Luis Y/O Bruna Borel Luis Gabriel', 'Bruna', '2021-11-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('421230', 'Silvia Alejandra', 'Rodriguez', '2021-11-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('422311', 'Tejada Carlos Cesar', 'Paez', '2021-11-26', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('425354', 'Marco Andres', 'Chevalley', '2021-12-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('425534', 'Mauro Luis', 'Ramirez', '2021-12-21', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('429125', 'Fabrizio Roberto', 'Sachetto', '2022-01-20', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('429800', 'Marquez Cesar Ulises', 'Echeverria', '2022-01-25', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('430713', 'Gianina Natali', 'Rodriguez', '2022-02-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('434544', 'Maximiliano', 'Disandro', '2022-02-24', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('436507', 'Pablo Nicolas', 'Melero', '2022-03-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('436591', 'Nancy Lucia', 'Clozza', '2022-03-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('437744', 'Juan Ignacio', 'Echezarreta', '2022-03-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('438867', 'Ana Belen', 'Murua', '2022-03-28', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('442084', 'Carlos', 'Gerez', '2022-04-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('442818', 'Adriana Griselda', 'Galiano', '2022-04-25', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('442840', 'Sabrina Gabriela', 'Freytes', '2022-04-25', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('443905', 'Mariana', 'Peralta', '2022-05-02', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('446206', 'Jorgelina Laura', 'Blanco', '2022-05-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('446579', 'Matias Maximiliano', 'Perez', '2022-05-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('446706', 'Agustina', 'Mauro', '2022-05-19', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('449747', 'Maria Belen', 'Cuppi', '2022-06-02', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('456664', 'Elías', 'Genaro', '2022-07-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('459133', 'Diego Alejandro .', 'Perez', '2022-07-21', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('459537', 'Noel Hernán', 'Fissore', '2022-07-22', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('462433', 'Ezequiel', 'Panigazzi', '2022-08-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('465539', 'Emilio Andres', 'Boella', '2022-08-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('467885', 'Guillermo Rodrigo', 'Falco', '2022-09-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('468061', 'Nadia Ines', 'Quinteros', '2022-09-02', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('470485', 'Francisco Elias', 'Alcayde', '2022-09-19', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('470813', 'Brenda Anabel', 'Fernandez', '2022-09-20', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('472294', 'Christian Javier', 'Boico', '2022-09-28', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('473082', 'Maximiliano Javier', 'Gamboa', '2022-10-04', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('473251', 'Rodolfo Alejandro', 'Vazquez', '2022-10-05', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('473295', 'Agostina', 'Vita', '2022-10-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('474103', 'Jose Hector', 'Romero', '2022-10-12', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('475429', 'Gerardo Ivan', 'Delgenio', '2022-10-20', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('479096', 'Lucila', 'More', '2022-11-17', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('479242', 'Maria Gabriela', 'Bossina', '2022-11-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('480386', 'Fabian Alejandro', 'Calvano', '2022-11-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('483725', 'Micaela Soledad', 'Palermo', '2022-12-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('487108', 'Serenela', 'Chulibert', '2023-01-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('487303', 'Talia Anahi', 'Sanchez', '2023-01-11', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('489901', 'Mariela Ivon', 'Macario', '2023-01-19', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('490452', 'Gonzalo Andres', 'Barrionuevo', '2023-01-20', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('490556', 'Dario', 'Aronovich', '2023-01-20', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('492571', 'Luciana Del Valle', 'Bauer', '2023-01-25', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('492912', 'Maria Sol', 'Oliveto', '2023-01-26', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('497329', 'Cintia Lorena', 'Samperi', '2023-02-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('499654', 'Nicolas Jonathan', 'Heredia', '2023-02-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('501121', 'Berardo Carolina Eugenia', 'Falcon', '2023-02-14', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('502356', 'Leilen Ailen', 'Ragu', '2023-02-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('504400', 'Viera Miguel Angel', 'Gamboa', '2023-02-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('504568', 'Josefina Maria Mercedes', 'Acevedo', '2023-02-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('504849', 'Ezequiel', 'Grosso', '2023-02-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('504988', 'Mirta Susana', 'Carus', '2023-02-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('505001', 'Carus Jon Antolin', 'Guevara', '2023-02-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('505455', 'Matias', 'Tedeschi', '2023-03-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('505696', 'Facundo Ezequiel', 'Palermo', '2023-03-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('510613', 'Guillermo Sebastian', 'Delicia', '2023-03-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('511261', 'Cecilia María José', 'Fernández', '2023-03-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('511289', 'Vanesa Valeria', 'Martinez', '2023-03-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('512845', 'Ana Lucia', 'Aguirre', '2023-03-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('514607', 'Lencina Lucrecia Paola', 'Gomez', '2023-04-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('516000', 'Emilio Jose', 'Dubini', '2023-04-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('517907', 'María Ester', 'Sardiello', '2023-04-12', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('518496', 'Maria Belen', 'Clerico', '2023-04-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('518752', 'Ignacio Jose', 'Sabbag', '2023-04-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('519879', 'German', 'Schmukler', '2023-04-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('528867', 'Gabriela Viviana', 'Bertolani', '2023-04-28', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('533026', 'Juan Francisco', 'Matkovic', '2023-05-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('537795', 'Alma Lucía', 'Alvarez', '2023-05-09', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('546810', 'Ernesto Fabian', 'Fernandez', '2023-05-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('547380', 'Silvana Maria De Lujn', 'Andres', '2023-05-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('547395', 'Martin Fabricio', 'Palermo', '2023-05-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('550074', 'Maria Alejandra', 'Andres', '2023-05-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('550973', 'Anahi Lilian', 'Lopez', '2023-05-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('551089', 'Jesica Paola', 'Kloster', '2023-05-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('551257', 'Maira Ayelén', 'Casaña', '2023-05-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('551946', 'Eduardo Alberto', 'Velazquez', '2023-05-31', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('552824', 'Perla Asuncion', 'Yedro', '2023-06-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('563263', 'César José', 'Jakubowski', '2023-06-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('567157', 'Walter Roman', 'Mattioli', '2023-06-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('568211', 'Fernando Andres', 'Gomez', '2023-06-29', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('577118', 'Laura Alejandra', 'Correa', '2023-07-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('580875', 'Valeria', 'Agostinelli', '2023-07-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('583524', 'Virginia', 'Gschwind', '2023-07-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('587298', 'Mauricio Agustin', 'Carletti', '2023-07-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('587398', 'Gaston Mauricio', 'Piccione', '2023-07-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('588045', 'Graciela Beatriz', 'Tita', '2023-07-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('588046', 'Monica Silvina', 'Tita', '2023-07-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('591764', 'Aldana Beatriz', 'Sosa', '2023-07-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('593429', 'Daiana', 'Blanco', '2023-07-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('593463', 'Maria Celeste .', 'Sanchez', '2023-07-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('593519', 'Noelia', 'Espinosa', '2023-07-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('595309', 'Sabrina Gisel', 'Blanco', '2023-07-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('597479', 'Veronica Mercedes', 'Fernandez', '2023-07-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  (null, 'Maria Jose', 'Siebenhar', '2023-07-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('603412', 'Leon Laura Patricia', 'Pedroza', '2023-08-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('605457', 'Sandra Beatriz', 'Biccai', '2023-08-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('605517', 'Natalia Judith', 'Rebolledo', '2023-08-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('607680', 'Carlos Javier', 'Ale', '2023-08-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('608761', 'Claudio Alejandro Y/O Sexer Fernando Daniel', 'Sexer', '2023-08-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('609693', 'Gustavo Fernando', 'Peñaloza', '2023-08-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('618159', 'Maria Celeste', 'Mirada', '2023-08-09', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('625069', 'Elias David', 'Abate', '2023-08-14', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('626215', 'Ariadna Natalia', 'Ciammarriello', '2023-08-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('628150', 'Francisco Jose', 'Balsa', '2023-08-15', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('628986', 'Maximiliano Martin', 'Ferreyra', '2023-08-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('633007', 'Maria De Los Angeles', 'Camarasa', '2023-08-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('634558', 'Jorge Daniel', 'Ale', '2023-08-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('634776', 'Rocca Jose Ignacio', 'La', '2023-08-18', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('649589', 'Renata Maria', 'Tarsetti', '2023-08-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('649882', 'Adrian Matias', 'Ternavasio', '2023-08-29', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('658638', 'Valeria Vanesa', 'Bustamante', '2023-09-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('661139', 'Dante', 'Ausili', '2023-09-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('661688', 'Florencia Ayelen', 'Reim', '2023-09-06', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('662556', 'Silvana Florencia', 'Viano', '2023-09-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('665361', 'Diego Pablo', 'Bembo', '2023-09-08', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('679093', 'Nicolas', 'Profeti', '2023-09-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('682775', 'Umberto Nahuel', 'Santini', '2023-09-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('685158', 'Bella Roberto Pablo', 'Di', '2023-09-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('685464', 'Giuliana', 'Fava', '2023-09-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('686953', 'Albelo Luis Alfredo', 'Gatica', '2023-09-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('687763', 'Carlos Javier', 'Andrade', '2023-09-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('689195', 'Matias Sebastian', 'Basualdo', '2023-10-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('694738', 'Carlos Alberto', 'Andrade', '2023-10-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('709966', 'Sol', 'Petrungaro', '2023-10-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('712144', 'Yamila Valeria', 'Fussi', '2023-10-12', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('712741', 'Morena Yuliana', 'Postiglione', '2023-10-12', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('718130', 'Salazar Juan Enrique', 'Gomez', '2023-10-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('718474', 'Karim José', 'Pisacco', '2023-10-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('718655', 'Carelina Ariana', 'Gonzalez', '2023-10-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('723022', 'Constantino Demetrio', 'Dretakis', '2023-10-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('723438', 'Marcelo Ruben', 'Rossia', '2023-10-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('724734', 'Roxana Pamela', 'Romero', '2023-10-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('725155', 'Luciano', 'Ricca', '2023-10-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('725542', 'Chapero Andrea', 'Romero', '2023-10-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('726611', 'Favia Juan Pablo', 'De', '2023-10-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('728456', 'Javier Carlos', 'Baroli', '2023-10-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('729135', 'Marisol', 'Angeloni', '2023-10-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('107072', 'Confort Srl', 'Rosario', '2023-10-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('738567', 'Luciano José María', 'Aramberry', '2023-10-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('751855', 'Andrea Viviana', 'Massei', '2023-11-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('752022', 'Carlos Alberto ......', 'Sanchez', '2023-11-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('752140', 'Julian Ignacio', 'Nebreda', '2023-11-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('752826', 'Danisa Laura', 'Chevalley', '2023-11-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('107334', 'Sociedad Anonima', 'Realico', '2023-11-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('757538', 'Mauro Joel', 'Correa', '2023-11-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('760863', 'Rafael', 'Elgorriaga', '2023-11-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('764386', 'Maia Emeli', 'Massella', '2023-11-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('765020', 'Maria De Los Angeles', 'Murray', '2023-11-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  (null, 'Carina Elisabet', 'Gohlke', '2023-11-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('766708', 'Raul Horacio', 'Sabetti', '2023-11-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('766875', 'Brigida', 'Colombini', '2023-11-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('767612', 'Milagros Yamila', 'Aguirre', '2023-11-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('769243', 'Matías Ezequiel', 'Massella', '2023-11-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('776908', 'Tomas', 'Cisnero', '2023-12-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('777438', 'Veronica Soledad', 'Piovesan', '2023-12-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('778881', 'Emilio Fernando', 'Chevalley', '2023-12-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('778884', 'Román Norberto', 'Ardisson', '2023-12-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('778975', 'Mauro Alejandro', 'Vechi', '2023-12-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('782188', 'Marcos', 'Balbiani', '2023-12-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('784332', 'Héctor Juan', 'Occelli', '2023-12-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('785089', 'Rodrigo Agustin', 'Esquivel', '2023-12-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('785090', 'Maria Elena', 'Chevalley', '2023-12-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('788399', 'Elizabeth Nerea', 'Almada', '2023-12-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('789407', 'Marcelo Adrian', 'Principe', '2023-12-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('790215', 'Maria Eugenia', 'Chulibert', '2023-12-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('790278', 'Franco Armando', 'Bertoglio', '2023-12-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('790328', 'Horacio Javier', 'Caula', '2023-12-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('791319', 'Norberto Edgardo', 'Puntonet', '2023-12-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('793232', 'Monica Patricia', 'Correa', '2023-12-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('794670', 'Mariel Guadalupe', 'Compagnucci', '2023-12-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('796643', 'Liliana Ester', 'Wilchen', '2023-12-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('798905', 'Lucas Miguel', 'Bustos', '2023-12-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('799858', 'Edgar Jose', 'Pisacco', '2023-12-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('799860', 'Delia', 'Pazzaglia', '2023-12-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('801916', 'Leonardo', 'Suarez', '2023-12-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('802016', 'Ayelen Florencia', 'Scataglini', '2023-12-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('802031', 'Juan Carlos Marcelino', 'Bertoglio', '2023-12-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('808996', 'Juan Manuel', 'Varas', '2024-01-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('809145', 'Koberstein Marisel', 'Dopslaff', '2024-01-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('809442', 'Stefania', 'Marquez', '2024-01-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('810066', 'Lucia Florencia', 'Barreto', '2024-01-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('811112', 'Celeste', 'Sanabria', '2024-01-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('816680', 'Lucas Damian', 'Flores', '2024-01-08', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('818430', 'Federico Andrés', 'Marquez', '2024-01-09', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('821258', 'Monica Susana', 'Castillo', '2024-01-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('822185', 'Diego Armando Francisco', 'Pezzelatto', '2024-01-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('107954', 'Srl', 'Afinium', '2024-01-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('833992', 'Carolina .', 'Manno', '2024-01-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('834207', 'Maria Esthelvina', 'Cruz', '2024-01-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('834751', 'Agustin', 'Damiano', '2024-01-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('835857', 'Lorena Veronica', 'Castro', '2024-01-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('837888', 'Noelia Andrea', 'Leiva', '2024-01-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('838823', 'Zapata Icarek Abraham', 'Castro', '2024-01-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('839865', 'Oscar Alberto', 'Tonini', '2024-01-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('840201', 'Santos Maria Luisa', 'Dos', '2024-01-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('840881', 'Melina Fernanda', 'Martinotti', '2024-01-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('841893', 'Luciano Agustin', 'Lambert', '2024-01-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('843350', 'Carlos Daniel', 'Sarina', '2024-01-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('847236', 'Barbara Belen', 'Pafundi', '2024-01-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('855143', 'Flavia Gabriela', 'Riffel', '2024-02-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('857828', 'Julieta', 'Tedesco', '2024-02-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('859002', 'Lorena Constanza', 'Saco', '2024-02-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('859944', 'Ramiro Maximiliano', 'Obregon', '2024-02-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('866871', 'Hernan', 'Guidi', '2024-02-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('869354', 'Briñon Felipe', 'Panichelli', '2024-02-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('872318', 'Aldana Rocio', 'Cesaretti', '2024-02-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('872483', 'Florencia Laura', 'Pereyra', '2024-02-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('875225', 'Marcelo Antonio', 'Pereyra', '2024-02-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('876653', 'Maria Alejandra', 'Oteiza', '2024-02-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('876741', 'Sergio Fabricio', 'Rosales', '2024-02-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('877501', 'Juan Sebastian', 'Nieva', '2024-02-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('877624', 'Leonardo Osvaldo', 'Peri', '2024-02-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('877712', 'Romina Soledad .', 'Rodriguez', '2024-02-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('878040', 'Simn', 'Braconi', '2024-02-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('881134', 'Marcela Paula', 'Curro', '2024-02-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('884019', 'Bernardo', 'Gogna', '2024-02-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('884599', 'Luis Alberto', 'Planjar', '2024-03-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('887687', 'Maria Elena', 'Sarraude', '2024-03-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('889200', 'Sanabria Juan', 'Cándido', '2024-03-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('893242', 'Carla', 'Torregiani', '2024-03-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('898800', 'Carla Maricel', 'Maniel', '2024-03-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('900624', 'Maria Victoria', 'Allegri', '2024-03-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('903553', 'Gustavo Fabian ...', 'Fernandez', '2024-03-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('906600', 'Oscar Alberto Y/O Ruiz Sonia Berta', 'Torres', '2024-03-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('918480', 'Joaquin', 'Ranedo', '2024-04-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('922031', 'Cristian Adrian', 'Garay', '2024-04-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('925439', 'Andrea Ayelen', 'Torri', '2024-04-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('931694', 'Agustin Fernando', 'Gomez', '2024-05-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('940904', 'Hernan Roberto', 'Gaggino', '2024-05-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('941803', 'Alvarez Ignacio Matias', 'Borja', '2024-05-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('944357', 'Eber Dante', 'Ceccotti', '2024-05-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('953924', 'Maria Marta', 'Cordero', '2024-06-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('955122', 'Pablo Jose', 'Intelangelo', '2024-06-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('959936', 'Denise Araceli', 'Chauderlot', '2024-06-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('962015', 'Martin Ariel', 'Arroyo', '2024-06-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('962016', 'Adriana Noemi', 'Delgado', '2024-06-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('965038', 'Alejandra Delma', 'Toso', '2024-06-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('975547', 'Maria Fernanda', 'Nievas', '2024-06-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('109347', 'Sas', 'Zafiro', '2024-06-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('989223', 'Tamara', 'Saldaña', '2024-06-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('992736', 'Cintia Maria Nazaret', 'Nardone', '2024-07-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('993898', 'Galdo Ana Carolina', 'Boj', '2024-07-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('993984', 'Pablo Eduardo', 'Larocca', '2024-07-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('995285', 'Lisandro Angel', 'Chinellato', '2024-07-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('996358', 'Martin', 'Garcia', '2024-07-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1009270', 'Paolo', 'Boarelli', '2024-07-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1010021', 'Castillo Maria De Los Angeles', 'Del', '2024-07-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1010112', 'Carmen Lucia', 'Brehinier', '2024-07-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1019250', 'Mirta Del Valle', 'Fabbiani', '2024-07-16', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1021535', 'Sofia', 'Arceo', '2024-07-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1025021', 'Carina Graciela', 'Cambria', '2024-07-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1029889', 'Johanna Belen', 'Soteras', '2024-07-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  (null, 'Serenela', 'Chulibert', '2024-07-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1043449', 'Andres Javier', 'Blanquez', '2024-07-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1045692', 'Alexis Federico', 'Wagner', '2024-07-31', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1049006', 'Fiscina Alejandro', 'Buccella', '2024-08-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1063247', 'Juan Manuel', 'Cano', '2024-08-09', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('1080270', 'Maria Del Carmen', 'Cortez', '2024-08-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1090220', 'Judit Eliana', 'Rovere', '2024-08-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1091288', 'Florencia Marilin', 'Ludueña', '2024-08-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1092915', 'Nicolas', 'Arnaldi', '2024-08-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1104449', 'Bruno Jose', 'Krumbein', '2024-09-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1111371', 'Matias Damian', 'Urreli', '2024-09-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1121687', 'Mercedes Beatriz', 'Tropfenbaum', '2024-09-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1126759', 'Maria Fernanda', 'Antonelli', '2024-09-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1134151', 'Julio Anibal', 'Andisco', '2024-09-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1140559', '- Chinellato Lisandro Angel', 'Cera', '2024-10-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('110102', 'Sa', 'Krumbein', '2024-10-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1151384', 'Matias Ezequiel', 'Borda', '2024-10-09', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1155214', 'Maria De Los Milagros', 'Gomez', '2024-10-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1156720', 'César Daniel', 'Montiel', '2024-10-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1183689', 'Mia Joselin', 'Quiroga', '2024-11-07', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('1193984', 'Matias Omar Y/O Leone Ana Laura', 'Aghem', '2024-11-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1211505', 'Silvia Natalia', 'Sobol', '2024-11-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1212293', 'Barbara', 'Juster', '2024-11-29', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1214068', 'Renzo', 'Tagliafico', '2024-12-02', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1216955', 'Maria Eugenia', 'Court', '2024-12-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1229386', 'Sofía', 'Liñan', '2024-12-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1232519', 'Juan Matias', 'Biscayart', '2024-12-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1254057', 'Jorge Alberto', 'Blanco', '2025-01-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1266898', 'Delvalle Blanca Marisol', 'Fernandez', '2025-01-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1267599', 'Juan Pablo', 'Luccioni', '2025-01-14', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1269990', 'Micael', 'Benito', '2025-01-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1272958', 'Coelho Gonzalo Sebastian', 'Rodriguez', '2025-01-17', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1277760', 'Barbara Estela', 'Massarutto', '2025-01-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1289802', 'Juan Carlos', 'Peralta', '2025-01-30', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1290913', 'Rodrigo', 'Avendaño', '2025-01-31', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1296647', 'Ariana', 'Pagani', '2025-02-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1312620', 'Gonzalo Omar', 'Gamerro', '2025-02-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1316191', 'Zuluaga Maria Amelia', 'Macedo', '2025-02-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('111200', 'Saic', 'Nitub', '2025-02-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1338509', 'Nora Noemi', 'Lottgering', '2025-03-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1343597', 'Lisandro Pablo', 'Romero', '2025-03-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1343957', 'Maximiliano', 'Elsegood', '2025-03-25', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1346984', 'De Griendt Virginia', 'Van', '2025-03-28', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1350335', 'Jorge Jeremias', 'Mingorance', '2025-04-01', 'Agos', 'mis-clientes', 'reasignado', null, null, null, 'reasignaciones', 'Agos', false, null, null),
  ('1351658', 'Jorgelina Mercedes', 'Canteli', '2025-04-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1357740', 'Melina Maria', 'Maggi', '2025-04-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('161569', 'Ingenieria Srl', 'H2T', '2025-05-15', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('161702', 'Viajes Srl', 'Focus', '2025-06-09', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1414119', 'Carmen Lujan', 'Abad', '2025-06-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1419764', 'Luciana Maria', 'Mori', '2025-06-24', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1437535', 'Norberto Edgardo Y/O Rodriguez Patricia Nora', 'Puntonet', '2025-07-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1445630', 'Sergio Jesus Y/O Viano Silvana Florencia', 'Viano', '2025-08-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1449884', 'Devora Soledad', 'Chico', '2025-08-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1451126', 'Simone Terezinha', 'Walginski', '2025-08-12', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1452083', 'Miriam Gabriela', 'Benavidez', '2025-08-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1452088', 'Alicia Mabel', 'Suarez', '2025-08-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1454804', 'Mijich Leticia Y/O Peralta Mijich María Eugenia Y/O Mijich Gladys Maria', 'Peralta', '2025-08-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1460059', 'Virginia Laura', 'Orieta', '2025-08-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1460261', 'María Belén', 'Renna', '2025-08-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1460535', 'Cristina Hilda', 'Perez', '2025-08-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1460740', 'Mijich Leticia', 'Peralta', '2025-08-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1462765', 'Agostina', 'Prus', '2025-09-01', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1469606', 'Brambilla Maria Eugenia', 'Vidal', '2025-09-10', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1476564', 'Rolando Daniel', 'Martinez', '2025-09-23', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1486092', 'Catalina Y/O Romero Roxana Pamela', 'Fossi', '2025-10-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1507540', 'Maria Emilia', 'Ale', '2025-11-03', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1519242', 'Kissam Agustin Dario', 'Trowell', '2025-11-20', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1521755', 'Mauren Lorena Y/O De La Fuente José Marco', 'Ceccotti', '2025-11-27', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1527211', 'Lucio Claudia Marina', 'Santos', '2025-12-05', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1534235', 'Ferreira Leandro Ezequiel', 'Chamorro', '2025-12-18', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1534864', 'Giselle Elizabeth', 'Alferez', '2025-12-19', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1537615', 'Ignacio', 'Luque', '2025-12-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1544850', 'Norma Carina Y/O Rodriguez Rocio Maria', 'Bittar', '2026-01-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1545056', 'Agostina', 'Cordi', '2026-01-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1559071', 'Rodrigo Javier', 'Rios', '2026-01-21', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1562241', 'Joel Alejandro', 'Krat', '2026-01-26', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1572097', 'Mariana Lucia', 'Garces', '2026-02-04', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1597863', 'Victoria', 'Rabin', '2026-03-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1611366', 'Gabriela Carina', 'Medina', '2026-04-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1612177', 'Malvina Maria', 'Maggi', '2026-04-06', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1612991', 'Mariana', 'Perez', '2026-04-07', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1616928', 'Maria Regina', 'Baroli', '2026-04-13', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1618360', 'Florencia', 'Sanguineti', '2026-04-15', 'Agos', 'equipo-fernanda', 'propio', null, 'indemnizacion', 'Amiga de Fernanda. Indemnización. Pone $60M ARS en instrumentos líquidos para vivir. Se separa una parte a largo plazo.', null, 'Agos', false, null, null),
  ('1623140', 'Daniela Liliana', 'Fusiano', '2026-04-22', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1639838', 'Maria Lujan', 'Vicente', '2026-05-18', 'Agos', 'equipo-fernanda', 'propio', null, null, 'Amiga de Fernanda. Ahorros mínimos. Profesora de yoga. Poca capacidad de ahorro.', null, 'Agos', false, null, null),
  ('1647912', 'Veronica Laura', 'Wahlberg', '2026-06-01', 'Agos', 'equipo-fernanda', 'propio', null, null, 'Venta de casa: USD 160.000. Saca USD 20.000 para gastos y cambio de auto. El resto (USD 140.000) empieza a construir cartera en el broker — se le entrega un plan.', null, 'Agos', false, null, null),
  ('1653121', 'Florencia Lucia', 'Garay', '2026-06-08', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('1657133', 'Carolina', 'Hernandez', '2026-06-11', 'Agos', 'equipo-fernanda', 'propio', null, 'indemnizacion', 'Periodista. Indemnización. Cuenta de manejo de liquidez. Total: $28M ARS — pone $14M ahora. Tiene cuenta en IOL con Federico (asesor del equipo Fernanda). Tiene ON y CEDEARs.', null, 'Agos', false, null, null),
  ('1657477', 'Camila Ayelen', 'Bono', '2026-06-11', 'Agos', 'mis-clientes', 'propio', null, null, null, null, 'Agos', false, null, null),
  ('72930', 'Jose Ignacio', 'Matarazzo', '2017-05-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('25996', 'Luciano Fabio', 'Papurello', '2018-12-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('26248', 'Corbella Federico Manuel', 'Lopez', '2019-01-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('268411', 'Leonardo Alberto', 'Cano', '2019-06-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('273084', 'Silvia Susana', 'Tiscornia', '2019-08-16', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('29099', 'Lucas Manuel', 'Salomone', '2019-08-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('29432', 'Daniel Alberto', 'Milia', '2019-09-02', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('278019', 'Daniel Helder', 'Morero', '2019-09-09', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('30395', 'Romina Vanesa', 'Ruggiero', '2019-09-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('30650', 'Diego Antonio', 'Gallo', '2019-09-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('30804', 'Herrera Felix Alberto', 'Molina', '2019-09-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('30891', 'Agustin Ignacio', 'Rubistein', '2019-09-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('31036', 'Diego Hernan', 'Marzol', '2019-09-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('281776', 'Agustina', 'Salomone', '2019-09-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('31657', 'Luciano Martin', 'Rial', '2019-09-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('32021', 'Viviana Ines', 'Dorado', '2019-09-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('32035', 'Blanco Nicolas Pedro', 'Berteuris', '2019-09-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('33085', 'Torres Iris Veronica', 'Moyano', '2019-09-23', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('34107', 'Bruno Ariel', 'Todone', '2019-09-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('34619', 'Carou Jose Y/O Santoro Magali Elizabeth', 'Rodriguez', '2019-10-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('297366', 'Joaquin Ignacio', 'Bogliolo', '2019-10-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('35986', 'Magalhaes Monique', 'Portela', '2019-11-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('302098', 'Horacio Enrique', 'Vanzetti', '2019-11-29', 'Tiago', 'equipo-gallo', 'reasignado', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('37123', 'Alberto Elias', 'Schnaiderman', '2020-01-02', 'Tiago', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', true, 'false', 'true'),
  ('38103', 'Soler Marianela Amancay', 'Garcia', '2020-01-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('38313', 'Bernardo', 'Cicconi', '2020-01-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('39133', 'Mura Maria Victoria', 'Aladro', '2020-02-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('325838', 'Reinoso Carlos Roberto', 'Sanchez', '2020-05-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('334165', 'Luca Pablo Jorge', 'De', '2020-06-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('334166', 'Omar Carlos', 'Pistritto', '2020-06-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('336636', 'Maria Cristina', 'Brumec', '2020-07-06', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('340321', 'Luis Agustin', 'Bogliolo', '2020-07-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('342717', 'Rivero Yamandu Ideal', 'Pecci', '2020-08-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('342734', 'Karina Judith', 'Jaimes', '2020-08-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('343096', 'Maria Laura', 'Tomaszewski', '2020-08-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('343491', 'Ana Maria', 'Venica', '2020-08-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('343692', 'Viviana Raquel', 'Iannini', '2020-08-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('344356', 'Maria Raquel', 'Almiron', '2020-08-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('344357', 'Monica Andrea', 'Iannini', '2020-08-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('344611', 'Coro Ana Maria', 'De', '2020-08-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('344723', 'Maria Agustina', 'Cano', '2020-08-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('346589', 'Nadeida', 'Goñi', '2020-09-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('346958', 'Gabriela', 'Garay', '2020-09-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('347074', 'Monica Vanesa', 'Santillan', '2020-09-08', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('347582', 'Souto Juan Cruz', 'Fernandez', '2020-09-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('348698', 'Ezequiel', 'Martin', '2020-09-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('349274', 'Hector Manuel', 'Salomone', '2020-09-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('351407', 'Ferreyra Claudio Matias', 'Gonzalez', '2020-10-08', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('358348', 'Rene Gustavo', 'Flores', '2020-11-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('358858', 'Agostina Gloria', 'Ferretty', '2020-11-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('359670', 'Carlos Matias', 'Spadea', '2020-11-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('364535', 'Jorge Mariano', 'Gestoso', '2020-12-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('364716', 'Demian Matias', 'Niedfeld', '2020-12-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('364979', 'Nestor Ariel', 'Gulli', '2020-12-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('366274', 'Marcelo Jose', 'Denipoti', '2021-01-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('366748', 'Eugenio', 'Cicconi', '2021-01-06', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('368922', 'Nynatten Alejandro', 'Van', '2021-01-15', 'Diego', 'equipo-gallo', 'reasignado', 'moderado', null, null, null, 'Diego', false, 'false', 'false'),
  ('369362', 'Olga Maria Y/O Denipoti Claudio Ruben', 'Clerici', '2021-01-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('369416', 'Roberto Antonio Y/O Luppi Liliana Patricia', 'Casale', '2021-01-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('371193', 'Roberto Antonio', 'Casale', '2021-01-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('374219', 'Ezequiel Oscar', 'Quinteros', '2021-02-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('375778', 'Sofia Belen', 'Malga', '2021-02-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('375780', 'Diego', 'Tortora', '2021-02-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('378746', 'Luciana Belen', 'Gulli', '2021-03-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('381022', 'Pablo Amilcar', 'Lietti', '2021-04-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('382585', 'Adriana Laura Evelyn', 'Teves', '2021-04-15', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('384350', 'Abecasis Lucas Federico', 'Leoni', '2021-04-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('387151', 'Sergio Alejandro', 'Añon', '2021-05-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('388057', 'Jessica Lilia', 'Jacentiuk', '2021-05-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('102589', 'Water Solutions Srl', 'Hs', '2021-06-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('391824', 'Rosana Beatriz', 'Carnevale', '2021-06-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('396621', 'Jaimes Daiana Mariel', 'Jugo', '2021-07-16', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('401634', 'Luis Maria', 'Bogliolo', '2021-08-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('407601', 'Daniela Romina', 'Monteagudo', '2021-09-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('409704', 'Zulema Blanca', 'Guzman', '2021-09-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('411113', 'Santiago Ariel', 'Gulli', '2021-09-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('412518', 'Juan Sebastian', 'Gentini', '2021-10-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('412959', 'Godoy Andreina', 'Escobar', '2021-10-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('413326', 'Maria Jose', 'Valle', '2021-10-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('414755', 'Gabriela Eliana', 'Ciocoletto', '2021-10-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('416512', 'Montilla Maria Alejandra', 'Ramirez', '2021-10-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('417393', 'Marcela Edith', 'Apa', '2021-11-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('417407', 'Anabella Elizabeth Y/O Arjona Jorge Miguel', 'Tumbeiro', '2021-11-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('419059', 'Kevin Igal', 'Kreimberg', '2021-11-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('426021', 'Tufro Katherine', 'Muñoz', '2021-12-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('428200', 'Patricia Ines Y/O Armas Agustina Belen', 'Zato', '2022-01-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('429015', 'Melina Andrea', 'Redondo', '2022-01-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('431413', 'Carlos Alberto', 'Kaltembach', '2022-02-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('435002', 'Hernan Pablo', 'Rodriguez', '2022-03-02', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('437526', 'Ignacio', 'Véspoli', '2022-03-17', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('442950', 'Maria Celeste Y/O Redondo Lisandro Sebastian', 'Velasco', '2022-04-25', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('443536', 'Raimondo Pedro Matias', 'Di', '2022-04-28', 'Diego', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'false'),
  ('448702', 'Freites Katherine Andriana', 'Liebano', '2022-05-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('449618', 'Ana Laura', 'Aceval', '2022-06-01', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('452131', 'Mirta Rosa Esther', 'Gurevich', '2022-06-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('457411', 'Juaniquina Ricarda Y/O Flores Rene Gustavo', 'Flores', '2022-07-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Diego Antonio', 'Gallo', '2022-08-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Santiago Ariel', 'Gulli', '2022-08-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('471135', 'Aller Licán', 'Baldo', '2022-09-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('471424', 'Lisandro Sebastian', 'Redondo', '2022-09-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('477321', 'Jorge Javier', 'Izaguirre', '2022-11-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('479284', 'Sergio Alejandro Y/O Starna Romina Mariela', 'Añon', '2022-11-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Jorge Javier', 'Izaguirre', '2022-11-23', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('480822', 'Elisa Lina', 'Gaozza', '2022-12-01', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('483392', 'Fabian Daniel Y/O Colucci Maria De Las Nieves', 'Fente', '2022-12-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('484027', 'Offredi Agustina', 'Fernandez', '2022-12-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('484416', 'Juan Héctor', 'Vogel', '2022-12-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('104838', 'Srl', 'Jacel', '2022-12-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('489405', 'Bert Mauro Ariel', 'Di', '2023-01-18', 'Diego', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'false'),
  ('502225', 'Omar Alfredo', 'Taborga', '2023-02-17', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('502275', 'Federico Daniel', 'Favot', '2023-02-17', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('502752', 'Ana Marcelo Rodolfo Y/O Vazquez Brenda Cecilia', 'Santa', '2023-02-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('504658', 'Capua Emiliano Francisco', 'Di', '2023-02-27', 'Diego', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'false'),
  ('507950', 'Ana Camila Belén Y/O Santa Ana Marcelo Rodolfo', 'Santa', '2023-03-08', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('508190', 'Ana Fabian Horacio Y/O Santa Ana Marcelo Rodolfo', 'Santa', '2023-03-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('511126', 'Maria Constanza', 'Gnecco', '2023-03-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('511264', 'Somoza Jose Maria', 'Vera', '2023-03-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('519949', 'Jorge Luis', 'Farall', '2023-04-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('521818', 'Bryan Leonardo', 'Garcia', '2023-04-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('528030', 'Benitez Marlene Soledad', 'Lopez', '2023-04-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('528353', 'Ana Delicia', 'Fernandez', '2023-04-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('537862', 'Maria Victoria', 'Pensado', '2023-05-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('547315', 'Micaela Soledad Y/O Avila Leonel Ernesto', 'Esquivel', '2023-05-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('553778', 'Maria Laura', 'Brumec', '2023-06-02', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Rene Gustavo', 'Flores', '2023-06-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('574486', 'Maria Elena', 'Houston', '2023-07-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('575018', 'José Carlos', 'Varela', '2023-07-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('581912', 'Valperga Rodolfo Edgardo', 'Bunader', '2023-07-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('593485', 'Diego Daniel .', 'Duarte', '2023-07-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('600067', 'Daniel Omar', 'Acuña', '2023-07-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('622371', 'Nilda', 'Villafañe', '2023-08-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('661418', 'Barbara Marina', 'Grinspan', '2023-09-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('662535', 'Abritta Emiliano Catriel', 'Romero', '2023-09-06', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('679010', 'Moises Andres', 'Bravo', '2023-09-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('680286', 'Marisol Beatriz', 'Bertola', '2023-09-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('697141', 'Federico Enrique', 'Sica', '2023-10-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('718568', 'Paula Daniela', 'Grinspan', '2023-10-17', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('723980', 'Eduardo Miguel', 'Rives', '2023-10-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('725182', 'Carolina Jimena', 'Lopez', '2023-10-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('725531', 'Daniela Natalia', 'Mendez', '2023-10-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('725605', 'Lara Jazmin', 'Mazzolla', '2023-10-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Juan Héctor', 'Vogel', '2023-10-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('738028', 'Maria Agustina', 'Gnecco', '2023-10-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('760006', 'Guadalupe Magdalena', 'Coria', '2023-11-21', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Lisandro Sebastian', 'Redondo', '2023-11-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('765568', 'Gustavo Ruben', 'Cano', '2023-11-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Montilla Maria Alejandra', 'Ramirez', '2023-12-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('776464', 'Quiroga Gloria Ines', 'Arango', '2023-12-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('782751', 'Paola Vanesa Y/O Barile Alejandro Dario', 'Aranda', '2023-12-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Somoza Jose Maria', 'Vera', '2023-12-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('784087', 'Alfaro Sonia Olga', 'Lopez', '2023-12-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('786071', 'De La Fuente Mathias Nicolas', 'Rojas', '2023-12-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Marcelo Jose Y/O Cantagalli Viviana Gabriela', 'Denipoti', '2023-12-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('801834', 'Gustavo Genaro Y/O Demarchi Paola Lorena', 'Isabella', '2023-12-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('801938', 'Silvana Del Valle Y/O Denipoti Claudio Ruben', 'Ebel', '2023-12-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('806771', 'Fabio Daniel', 'Moriconi', '2024-01-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('811483', 'Justo Y/O Caro Evelyn Grisel', 'Daverio', '2024-01-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('811552', 'Maria Del Carmen', 'Lara', '2024-01-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('831205', 'Oscar', 'Canosa', '2024-01-17', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Melina Andrea', 'Redondo', '2024-01-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('850280', 'Jorge Guillermo', 'Vera', '2024-01-31', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Souto Juan Cruz', 'Fernandez', '2024-01-31', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('865662', 'Lina Maximina', 'Ezcurdia', '2024-02-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('890642', 'Hernan Ariel Y/O Benitez Marisa Viviana', 'Nuñez', '2024-03-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('108534', 'Servicios Integrales Srl', 'Cr', '2024-03-14', 'Diego', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'false'),
  ('899256', 'Maria Carolina', 'Laprida', '2024-03-15', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('902461', 'Gino', 'Vitale', '2024-03-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('903579', 'Ana Maria', 'Caceres', '2024-03-20', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, 'Más moderado', null, 'Diego', false, 'false', 'true'),
  ('906637', 'Xamena Gabriel Eduardo', 'Godoy', '2024-03-25', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('907510', 'Sergio Alejandro Y/O Balkenende Karin Cristina', 'Musso', '2024-03-26', 'Tiago', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'true'),
  ('908490', 'Luis Ruben Y/O Moriconi Fernando Ariel', 'Moriconi', '2024-03-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('908544', 'Abecasis Ezequiel Pedro', 'Fridman', '2024-03-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('909150', 'Florencia Beatriz', 'Carli', '2024-03-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('911106', 'Marcos .', 'Dartiguelongue', '2024-04-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('917413', 'Alejandro Javier', 'Samudio', '2024-04-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('919076', 'Pablo Sebastian', 'Guevara', '2024-04-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('924892', 'Griselda Alejandra', 'Cordes', '2024-04-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('927700', 'Ferrante Braian David', 'Lilli', '2024-04-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Alejandro Javier', 'Samudio', '2024-04-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('933108', 'Maria Eugenia De Los Angeles', 'Martin', '2024-05-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Xamena Gabriel Eduardo', 'Godoy', '2024-05-27', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('109142', 'Tecnologías Aplicadas Srl', 'Bambú', '2024-05-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('955526', 'Sandra Fabiana', 'Cardozo', '2024-06-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('962275', 'Rodriguez Manuel Nicolas', 'Jaime', '2024-06-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('985769', 'Andrea Fabiana', 'Martinez', '2024-06-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('986081', 'Maria Ester Y/O Redondo Lisandro Sebastian', 'Adaro', '2024-06-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('998537', 'Quintero Franmery Del Valle', 'Vivas', '2024-07-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1000598', 'Damian Isidoro', 'Dimarsico', '2024-07-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1004328', 'Jorge Hernan Y/O Servera Claudia Andrea Y/O Dartiguelongue Marcos', 'Dartiguelongue', '2024-07-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1009643', 'Elio Enrique', 'Ciaffoni', '2024-07-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('109435', 'Raddo Cilp Srl', 'Grupo', '2024-07-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1017812', 'Colmenares Sandra Josefina Y/O Borjas Colmenares Leonardo Enrique', 'Arocha', '2024-07-15', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  (null, 'Colmenares Sandra Josefina Y/O Borjas Colmenares Leonardo Enrique', 'Arocha', '2024-07-25', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1057560', 'Zoe Maitena', 'Julian', '2024-08-06', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1069045', 'Patricia Beatriz', 'Militello', '2024-08-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1085102', '- Cano Gustavo Ruben', 'Cera', '2024-08-23', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1085452', 'Miras Aldana Paola Y/O Suarez Maximiliano Ariel', 'Salorio', '2024-08-23', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1087773', 'Marcelo Fabian', 'Giordano', '2024-08-26', 'Tiago', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'true'),
  (null, 'Maria Victoria', 'Pensado', '2024-08-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1119423', 'Anibal Oscar', 'Carli', '2024-09-15', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1141605', 'Daniela Rosa', 'Fava', '2024-10-02', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, 'No mover mucho; evitar vender con pérdida', null, 'Diego', false, 'false', 'true'),
  ('1142675', 'Andrea María Cecilia', 'D', '2024-10-02', 'Diego', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'false'),
  ('1145667', 'Karina Vanesa', 'Kossoy', '2024-10-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1148848', 'Buffa Rafael Santiago', 'Brusa', '2024-10-07', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('1157947', 'Alejandro Hugo', 'Camacho', '2024-10-16', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1165667', 'Rosana Teresa', 'Magnano', '2024-10-22', 'Tiago', 'equipo-gallo', 'propio', 'riesgoso', null, null, null, 'Diego', false, 'false', 'true'),
  ('1166071', 'Alejandro Hugo Y/O Dominguez Fabiana Alicia', 'Camacho', '2024-10-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1179533', 'Furlan Javier Horacio', 'Galan', '2024-11-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1182635', 'Eduardo Ariel Y/O Actis Danna Griselda Fortunata Juana', 'Buompadre', '2024-11-06', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('1193985', 'Myriam Del Carmen', 'Banegas', '2024-11-15', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1204406', 'Marcelo Antonio', 'Cravero', '2024-11-25', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, null, null, 'Diego', false, 'false', 'true'),
  ('1206584', 'Eduardo Marcelo Y/O Giupponi Lorena Andrea', 'Gastaldi', '2024-11-26', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, 'Más moderado', null, 'Diego', false, 'false', 'true'),
  ('1207368', 'Diego Martin', 'Allo', '2024-11-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1211499', 'Agostina', 'Arnedo', '2024-11-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1227474', 'Gonzalo', 'Brondino', '2024-12-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1237486', 'Maria Pia', 'Salvatico', '2024-12-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1240451', 'Pablo Leonardo', 'Mansilla', '2024-12-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1245714', 'Ariel Alejandro', 'Boechat', '2024-12-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1256838', 'Gonzalo Y/O Bercic Maria', 'Brondino', '2025-01-06', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1258504', 'Juan Pablo', 'Arrighi', '2025-01-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1260282', 'Maximiliano Ariel', 'Piñeski', '2025-01-08', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1273952', 'Eduardo Marcelo', 'Allo', '2025-01-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1302213', 'Daniela Fabiana Y/O Bischoff Valentina', 'Bertino', '2025-02-10', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1304043', 'Natalia Y/O Oddo Leandro Lucero', 'Ventura', '2025-02-11', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1334971', 'Hernan Silvano', 'Segovia', '2025-03-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1380963', 'Luciana', 'Garay', '2025-04-24', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1410916', 'Iago Nicolás', 'Montecino', '2025-06-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1417167', 'Elba Juana', 'Guerrero', '2025-06-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1417805', 'Elsa Mabel', 'Guerrero', '2025-06-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1446094', 'Benitez Marlene Soledad Y/O Lopez Aida Elizabeth', 'Lopez', '2025-08-04', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1446817', 'Karen Nicole', 'Garcia', '2025-08-05', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1452816', 'Maria Angelica Y/O Hernandez Matias Sebastian Y/O Hernandez Maria Laura', 'Guerrero', '2025-08-14', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1460269', 'Elsa Mabel Y/O Demarchi Karina Mabel Y/O Demarchi Paola Lorena Y/O Dema', 'Guerrero', '2025-08-26', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1470994', 'Bernardo Jose', 'Grosso', '2025-09-12', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1474559', 'Montilla Maria Alejandra', 'Ramirez', '2025-09-19', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1478491', 'Cogley Ileana', 'Mindurry', '2025-09-25', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1511407', 'Carolina Andrea', 'Veltri', '2025-11-07', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1516735', 'Sebastian David Y/O Hernandez Maria Laura', 'Lubinski', '2025-11-17', 'Tiago', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', true, 'false', 'true'),
  (null, 'Sabolta Sergio Alejandro Y/O Starna Romina Mariela', 'Añón', '2025-12-17', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1541017', 'Manuel Carlos Y/O Fernandez Silvina Laura', 'Caceres', '2026-01-02', 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, 'Más moderado', null, 'Diego', false, 'false', 'true'),
  ('1557920', 'Evelyn', 'Murane', '2026-01-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1557948', 'Gaston Leonardo', 'Bonnet', '2026-01-20', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1592495', 'Andrea Antonella', 'Rubattino', '2026-03-03', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1595691', 'Mónica Fabiana', 'Cáceres', '2026-03-09', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1602165', 'Rodriguez Juan Cruz', 'Ocaña', '2026-03-18', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1608440', 'Maria Dolores', 'Martinez', '2026-03-30', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1609403', 'Ariel Hernan', 'Mendez', '2026-03-31', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1609721', 'Angel Amadeo Alberto', 'Villalba', '2026-04-01', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1614335', 'Laura Gimena Y/O Mendez Ariel Hernan', 'Mendez', '2026-04-08', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1623670', 'Ferreyra Malena', 'Rodriguez', '2026-04-22', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1626687', 'Ramírez Luis Alberto', 'Escobar', '2026-04-28', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1627607', 'Maria', 'Bercic', '2026-04-29', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1636282', 'Lautaro Joaquin', 'Barreiro', '2026-05-13', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1647901', 'Omar Alberto', 'Giletta', '2026-06-01', 'Diego', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', false, 'false', 'false'),
  ('1653375', 'Gabriela Maria Cristina Y/O Aldao Martin Jesus Y/O Aldao Magdalena Ine', 'Izquierdo', '2026-06-08', 'Tiago', 'equipo-gallo', 'propio', null, null, null, null, 'Diego', true, 'false', 'true'),
  (null, 'Mariano', 'Verra', null, 'Tiago', 'equipo-gallo', 'sin_reasignar', 'moderado', null, null, null, 'Diego', false, null, 'true'),
  (null, 'Valentina', 'Bischof', null, 'Tiago', 'equipo-gallo', 'propio', 'moderado', null, 'Más agresivo', null, 'Diego', false, null, 'true');
